export default {
	p_type:'P4',
	p_fraction:'P5',
	p_text_answer:'P12',
	p_wd_answer:'P7',
	p_part:'P14',
	p_hint:'P16',
	p_serial_number:'P17',
	p_wikipedia_page:'P24',
	p_wikipedia_section:'P20',
	p_wikipedia_oldid:'P21',
	p_translation_key:'P25',
	p_translation:'P26',
	
	q_i18n:'Q77',
	q_label_item_question:'Q3',
	q_multiple_choice_question:'Q4',
	q_html:'Q7',
	q_quiz:'Q8',
}